import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 10,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  titleText: {
    fontSize: 40,
    fontWeight: "bold",
    marginBottom: 10,
    marginTop: 10,
    marginHorizontal: 10,
    color: "#5878A7",
    textAlign: "center",
  },
  heading2: {
    fontSize: 30,
    fontWeight: "bold",
    textAlign: "center",
  },
  titleCaption: {
    fontSize: 40,
    fontWeight: "bold",
    textAlign: "center",
  },
  textInput: {
    height: 390,
    borderColor: "gray",
    borderWidth: 1,
    width: "80%",
    marginVertical: 20,
    padding: 10,
    backgroundColor: '#fcfcfc'
  },
  captionTextExercise: {
    fontSize: 20,
    marginBottom: 20,
    color: "#333333",
    textAlign: "center",
    width: "80%",
  },
  captionTextJournal: {
    fontSize: 25,
    color: "#333333",
    marginBottom: 5,
    textAlign: "center",
    width: "90%",
  },
  captionTextHome: {
    fontSize: 17.5,
    color: "#333333",
    marginTop: 20,
    textAlign: "center",
    width: "90%",
  },
  captionTextSleep: {
    fontSize: 17.5,
    color: "#333333",
    marginTop: 10,
    textAlign: "center",
    width: "80%",
  },
  listText: {
    fontSize: 17.5,
    color: "#333333",
    marginTop: 10,
    textAlign: "center",
    fontWeight: "bold",
  },
  regularText: {
    fontSize: 17.5,
    color: "#333333",
    marginTop: 10,
    textAlign: "center",
    width: "80%",
  },
  button: {
    backgroundColor: "rgb(99,162,95)",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
  },
  buttonText: {
    fontSize: 20,
    color: "#FFFFFF",
    textAlign: "center",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    borderRadius: 20,
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  exerciseContainer: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    marginBottom: 10,
    marginTop: 10,
    width: '90%'
  },
  exerciseTitle: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  exerciseDesc: {
    fontSize: 14,
    marginTop: 5,
  },
  exerciseDetails: {
    fontSize: 12,
    marginTop: 5,
    color: '#666',
  },
  loginTitle: {
    fontSize: 50,
    fontWeight: "bold",
    marginTop: 20,
    marginBottom: 20,
    marginHorizontal: 10,
    color: "#5878A7",
    textAlign: "center",
    fontFamily: 'Noteworthy',
  },
  loginTextInput: {
    borderColor: "transparent",
    borderWidth: 1,
    textAlign: 'left',
    height: 35,
    width: '80%',
    alignSelf: 'center',
    fontSize: 20,
    marginTop: 5,
    marginBottom: 10,
    backgroundColor: 'rgb(227,241,224)'
  },
});
